@startuml
class User
class Client
class Product

class User {
  id: INT
  email: VARCHAR
  username: VARCHAR
}

class Client{
  id: INT
  email: VARCHAR
  password: VARCHAR
  username: VARCHAR
  role: ARRAY
}

class Product{
  id: INT
  name: VARCHAR
  description: VARCHAR
  prix: FLOAT
}
Client "1" --- "0--*" User
@enduml
