@startuml
actor client
control systeme
database database

client -> systeme : GET /api/users/list
systeme -> systeme : Deserialize Data

alt data is valid
systeme -> database : get users list
database -> systeme:  return all users
systeme -> systeme : Serialize Data
systeme -> client : return users list
else
systeme -> client : Return error 400
end

@enduml
