@startuml
actor client
control systeme
database database

client -> systeme : GET /api/login_check
systeme -> systeme : Deserialize Data

alt data is valid
systeme -> database : check login credentials

alt credentials is valid
systeme->systeme: encode token jwt

systeme -> client : return jwt

else
systeme -> client : Return error 401
end

else
systeme -> client : Return error 400
end

@enduml
